### ISSUE TITLE
Add partition and cluster keys to live plays and shifts

### ISSUE THREAD

**Issue by gavh3** [the-data-base/nhl-data#46]
The benefit of partition and cluster keys is that queries will be faster, and fewer table partitions will be scanned when filters are applied.

AC:
- Add partition by config to shifts and live plays models
- Add cluster by config based on (1) high enough cardinality (distinct values) to effectively prune the table and (2) low enough cardinality for effective grouping of rows into the same partitions

**Comment by dmf95** [comment]
breaks meltano, probly cant do it
